# Generated by Django 5.2.11 on 2026-02-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_loginhistory_user_alter_otpverification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('LOCKED', 'Locked')], max_length=10),
        ),
    ]
