# Generated by Django 5.2.11 on 2026-03-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_loginhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('LOGIN_2FA', 'LOGIN_2FA'), ('RESET_PASSWORD', 'RESET_PASSWORD'), ('DELETE_ACCOUNT', 'DELETE_ACCOUNT'), ('ADMIN_REQUEST_VERIFY', 'ADMIN_REQUEST_VERIFY')], max_length=30),
        ),
    ]
