# Generated by Django 5.2.11 on 2026-03-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_otpverification_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('FIRST_LOGIN', 'FIRST_LOGIN'), ('LOGIN_2FA', 'LOGIN_2FA'), ('RESET_PASSWORD', 'RESET_PASSWORD'), ('DELETE_ACCOUNT', 'DELETE_ACCOUNT'), ('ADMIN_REQUEST_VERIFY', 'ADMIN_REQUEST_VERIFY')], max_length=30),
        ),
    ]
