# Generated by Django 5.2.11 on 2026-03-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_otpverification_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='purpose',
            field=models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('FIRST_LOGIN_OTP', 'FIRST_LOGIN_OTP'), ('LOGIN_2FA_OTP', 'LOGIN_2FA_OTP'), ('RESET_PASSWORD_OTP', 'RESET_PASSWORD_OTP')], max_length=30, null=True),
        ),
    ]
