# Generated by Django 5.2.11 on 2026-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loginhistory_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='purpose',
            field=models.CharField(blank=True, choices=[('LOGIN', 'LOGIN'), ('FIRST_LOGIN_OTP', 'FIRST_LOGIN_OTP'), ('LOGIN_2FA_OTP', 'LOGIN_2FA_OTP'), ('RESET_PASSWORD_OTP', 'RESET_PASSWORD_OTP'), ('OTP_SUBMISSION', 'OTP_SUBMISSION')], max_length=30, null=True),
        ),
    ]
