# Generated by Django 5.2.11 on 2026-03-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_loginhistory_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('FIRST_LOGIN_OTP', 'FIRST_LOGIN_OTP'), ('LOGIN_2FA_OTP', 'LOGIN_2FA_OTP'), ('RESET_PASSWORD_OTP', 'RESET_PASSWORD_OTP'), ('OTP_SUBMISSION', 'OTP_SUBMISSION')], default='LOGIN', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('LOCKED', 'LOCKED'), ('PENDING_OTP', 'PENDING_OTP')], max_length=20),
        ),
    ]
