# Generated by Django 5.2.11 on 2026-03-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_loginhistory_purpose_alter_loginhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
    ]
