# Generated by Django 5.2.11 on 2026-03-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_otpverification_attempt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('FIRST_LOGIN_OTP', 'FIRST_LOGIN_OTP'), ('LOGIN_2FA_OTP', 'LOGIN_2FA_OTP'), ('RESET_PASSWORD_OTP', 'RESET_PASSWORD_OTP'), ('RESET_PASSWORD', 'RESET_PASSWORD'), ('OTP_SUBMISSION', 'OTP_SUBMISSION')], max_length=30),
        ),
    ]
