# Generated by Django 5.2.11 on 2026-03-18 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.department'),
        ),
        migrations.AlterField(
            model_name='document',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.organization'),
        ),
    ]
