# Generated by Django 5.2.11 on 2026-03-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_document_dept_alter_document_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'LOGIN'), ('FIRST_LOGIN_OTP', 'FIRST_LOGIN_OTP'), ('LOGIN_2FA_OTP', 'LOGIN_2FA_OTP'), ('RESET_PASSWORD_OTP', 'RESET_PASSWORD_OTP'), ('RESET_PASSWORD', 'RESET_PASSWORD'), ('DELETE_ACCOUNT_OTP', 'DELETE_ACCOUNT_OTP'), ('UPDATE_2FA', 'UPDATE_2FA'), ('UPDATE_EMAIL', 'UPDATE_EMAIL'), ('OTP_SUBMISSION', 'OTP_SUBMISSION')], max_length=30),
        ),
    ]
