# Generated by Django 5.2.11 on 2026-03-19 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_loginhistory_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'analysis_result',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('rec_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_text', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], max_length=20)),
                ('act_name', models.CharField(max_length=255)),
                ('page_no', models.IntegerField()),
                ('line_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.analysisresult')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
    ]
