# Generated by Django 5.2.11 on 2026-03-19 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('finding_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_type', models.CharField(choices=[('GAP', 'Gap'), ('RISK', 'Risk')], default='GAP', max_length=10)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'finding',
                'ordering': ['finding_type', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='analysisresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='compliance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='document',
            field=models.OneToOneField(db_column='document_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='core.document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='raw_output',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('FIRST_LOGIN', 'FIRST_LOGIN'), ('LOGIN_2FA', 'LOGIN_2FA'), ('RESET_PASSWORD', 'RESET_PASSWORD'), ('DELETE_ACCOUNT', 'DELETE_ACCOUNT'), ('ADMIN_REQUEST_VERIFY', 'ADMIN_REQUEST_VERIFY'), ('EMAIL_CHANGE', 'EMAIL_CHANGE')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.CheckConstraint(condition=models.Q(('compliance_score__gte', 0), ('compliance_score__lte', 100)), name='compliance_score_range'),
        ),
        migrations.AddConstraint(
            model_name='analysisresult',
            constraint=models.CheckConstraint(condition=models.Q(('risk_level__in', ['LOW', 'MEDIUM', 'HIGH'])), name='risk_level_valid'),
        ),
        migrations.AddField(
            model_name='finding',
            name='result',
            field=models.ForeignKey(db_column='result_id', on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='core.analysisresult'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['result', 'finding_type'], name='finding_result_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.CheckConstraint(condition=models.Q(('finding_type__in', ['GAP', 'RISK'])), name='finding_type_valid'),
        ),
    ]
