# Generated by Django 5.2.11 on 2026-03-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_analysis_finding_schema'),
        ('core', '0020_auditlog'),
    ]

    operations = [
    ]
