# Generated by Django 5.2.11 on 2026-03-19 22:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_adminaccessrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminaccessrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RemoveConstraint(
            model_name='adminaccessrequest',
            name='admin_access_request_status_valid',
        ),
        migrations.AlterField(
            model_name='adminaccessrequest',
            name='failure_reason',
            field=models.TextField(blank=True, db_column='failure_reason', null=True),
        ),
        migrations.AlterField(
            model_name='adminaccessrequest',
            name='org_email',
            field=models.CharField(db_column='org_email', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminaccessrequest',
            name='requested_at',
            field=models.DateTimeField(db_column='requested_at', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='adminaccessrequest',
            name='verification_otp',
            field=models.ForeignKey(blank=True, db_column='verification_otp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.otpverification'),
        ),
        migrations.AlterField(
            model_name='adminaccessrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, db_column='verified_at', null=True),
        ),
        migrations.AddIndex(
            model_name='adminaccessrequest',
            index=models.Index(fields=['user', 'status'], name='admin_acces_user_id_8e2dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='adminaccessrequest',
            index=models.Index(fields=['status', 'requested_at'], name='admin_acces_status_c0f17b_idx'),
        ),
    ]
