# Generated by Django 5.2.11 on 2026-03-21 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_adminaccessrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDownload',
            fields=[
                ('download_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.UUIDField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_downloads', to='core.userprofile')),
            ],
            options={
                'db_table': 'report_downloads',
            },
        ),
    ]
