# Generated by Django 5.2.11 on 2026-03-21 14:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_adminaccessrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('deletion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email_snapshot', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('ACCOUNT', 'Account Deletion'), ('DATA_ONLY', 'Data Only')], default='ACCOUNT', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('erasure_summary', models.JSONField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='core.userprofile')),
            ],
            options={
                'db_table': 'deletion_request',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='deletion_re_user_id_fb2587_idx'), models.Index(fields=['status', 'requested_at'], name='deletion_re_status_ed0a2f_idx')],
            },
        ),
    ]
