# Generated by Django 5.2.11 on 2026-03-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_deletionrequest'),
        ('core', '0024_reportdownload'),
    ]

    operations = [
    ]
