# Generated by Django 5.2.11 on 2026-03-21 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_0024_deletionrequest_0024_reportdownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('share_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_with_email', models.EmailField(max_length=254)),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.report')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to='core.userprofile')),
            ],
            options={
                'db_table': 'report_shares',
            },
        ),
    ]
