# Generated by Django 5.2.11 on 2026-03-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_reportshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
