# Generated by Django 5.2.11 on 2026-04-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_auditlog_target_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='line_no',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='page_no',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='section',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='steps_to_achieve',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
    ]
