# Generated by Django 5.2.11 on 2026-04-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_recommendation_line_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10),
        ),
    ]
