# Generated by Django 5.2.11 on 2026-04-11 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auditlog_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.department'),
        ),
    ]
