# Generated by Django 5.2.11 on 2026-04-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auditlog_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportshare',
            name='access_token',
            field=models.TextField(unique=True),
        ),
    ]
