# Generated by Django 5.2.11 on 2026-04-13 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_reportshare_access_token'),
        ('core', '0030_report_dept'),
    ]

    operations = [
    ]
