# Generated by Django 5.2.11 on 2026-04-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_report_email_status_report_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccessrequest',
            name='original_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
