# Generated by Django 5.2.11 on 2026-04-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_original_email_to_admin_access_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='view_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
